spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board2?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: boarduser
    password: 1

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

